version: "3.8"
services:
  postgres:
    image: 'postgres:alpine'
    ports:
      - '5050:5432'
    volumes:
      - 'kanji-data:/var/lib/muzukanji-db'
    environment:
      - 'POSTGRES_DB=muzukanji'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'ENCODING=UTF8'
      - 'LANG=ja_JP.UTF-8'
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '5151:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@muzukanji.com'
      - 'PGADMIN_DEFAULT_PASSWORD=postgres'
    volumes:
      - 'kanji-data:/var/lib/pgadmin'
    depends_on:
      - 'postgres'
  keycloak:
    command: 'start-dev'
    image: 'quay.io/keycloak/keycloak:23.0.0'
    ports:
      - '5252:8080'
    environment:
      - 'DB_VENDOR=POSTGRES'
      - 'DB_DATABASE=muzukanji'
      - 'DB_USER=postgres'
      - 'DB_PASSWORD=password'
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=password'
    volumes:
      - 'kanji-data:/var/lib/keycloak'
    depends_on:
      - 'postgres'
volumes:
  kanji-data:
    driver: 'local'
