version: "3.8"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5050:5432"
    volumes:
      - kanji-data:/var/lib/muzukanji-db
    environment:
      POSTGRES_DB: muzukanji
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      ENCODING: UTF8
      LANG: a_JP.UTF-8
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5151:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    volumes:
      - kanji-data:/var/lib/pgadmin
    depends_on:
      - postgres
  keycloak:
    command: start-dev
    image: quay.io/keycloak/keycloak:23.0.0
    ports:
      - "5252:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_DATABASE: muzukanji
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASS}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASS}
    volumes:
      - kanji-data:/var/lib/keycloak
    depends_on:
      - postgres
  muzukanji:
    image: baqterya/muzukanji:latest
    ports:
      - "5555:5555"
    depends_on:
      - postgres
volumes:
  kanji-data:
    driver: local
