spring:
  datasource:
    url: jdbc:postgresql://172.17.0.1:5050/muzukanji
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-url: http://host.docker.internal:5252/realms/muzukanji
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-url}/protocol/openid-connect/certs
server:
  port: 5555
  error:
    include-message: always
jwt:
  auth:
    converter:
      resource-id: muzukanji-rest-api
      principle-attribute: preferred_username
